### ISSUE TITLE
Compiler warnings while installing

### ISSUE THREAD

**Issue by david-christiansen** [yasuyk/helm-company#16]
It seems that `helm-company` uses an obsolete variable. I get the following warnings when installing from MELPA:

```
In helm-company-run-show-doc-buffer:
helm-company.el:125:4:Warning: `display-buffer-function' is an obsolete
    variable (as of 24.3); use `display-buffer-alist' instead.

In helm-company-run-show-location:
helm-company.el:131:4:Warning: `display-buffer-function' is an obsolete
    variable (as of 24.3); use `display-buffer-alist' instead.
```

**Comment by yasuyk** [comment]
@david-christiansen  Sorry for the very very delayed response.

This issue is caused in [with-helm-display-same-window](https://github.com/yasuyk/helm-company/blob/a1a715289a5c230ff4d5513c7cdedac891a92168/helm-company.el#L118) function which use [display-buffer-function](https://github.com/emacs-helm/helm/blob/61c3192f6c2070fc62f373bc43c92d39c60b337e/helm.el#L5057). `with-helm-display-same-window` is defined in [helm](https://github.com/emacs-helm/helm). I'll just leave it as it is.
